[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs-18_x"]

[phases.install]
cmds = [
    "echo '=== LIMPIANDO CACHE ==='",
    "rm -rf bootstrap/cache/*.php",
    "rm -rf storage/framework/cache/*.php",
    "rm -f .env",
    "echo '=== INSTALANDO DEPENDENCIAS ==='",
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "npm install"
]

[phases.build]
cmds = [
    "echo '=== COMPILANDO FRONTEND ==='",
    "npm run build"
]

[start]
cmd = "echo '🎯 INICIANDO APLICACIÓN LARAVEL' && echo '📁 CONTENIDO DE bootstrap/cache/:' && ls -la bootstrap/cache/ && echo '🔍 VARIABLES DE ENTORNO:' && php -r \"echo 'DB_HOST: ' . (getenv('DB_HOST') ?: '❌ NO DEFINIDO') . PHP_EOL; echo 'DB_DATABASE: ' . (getenv('DB_DATABASE') ?: '❌ NO DEFINIDO') . PHP_EOL; echo 'DB_USERNAME: ' . (getenv('DB_USERNAME') ?: '❌ NO DEFINIDO') . PHP_EOL; echo 'DB_PASSWORD: ' . (substr(getenv('DB_PASSWORD') ?: '❌ NO DEFINIDO', 0, 5) . '...') . PHP_EOL;\" && echo '⏳ ESPERANDO 40 SEGUNDOS PARA CONEXIÓN BD...' && sleep 40 && echo '🚀 EJECUTANDO MIGRACIONES...' && php artisan migrate --force && echo '✅ INICIANDO SERVIDOR LARAVEL' && php artisan serve --host=0.0.0.0 --port=$PORT"