[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs-18_x"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "npm install"
]

[phases.build]
cmds = [
    "chmod -R 775 storage bootstrap/cache",
    "npm run build"
]

[start]
cmd = "sleep 20 && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"