[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs-18_x"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "php -r \"try { \\$pdo = new PDO('mysql:host=mysql.railway.internal;port=3306;dbname=railway', 'root', 'ZFWAcAQLMqDvuJfCqSXKvAMnMmiTCIyS'); echo '✅ CONEXIÓN EXITOSA'; } catch (Exception \\$e) { echo 'ERROR: ' . \\$e->getMessage(); }\" && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"