[phases.setup]
nixPkgs = [
    "php82", 
    "php82Packages.composer",
    "nodejs-18_x"
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --ignore-platform-reqs",
    "npm install"
]

[phases.build]
cmds = [
    "php artisan config:clear",
    "php artisan route:clear",
    "php artisan view:clear",
    "npm run build"
]

[start]
cmd = "php -r \"try { \\$pdo = new PDO('mysql:host=mysql.railway.internal;port=3306;dbname=railway', 'root', 'ZFWAcAQLMqDvuJfCqSXKvAMnMmiTCIyS'); echo '✅ BD Conectada'; } catch (Exception \\$e) { echo '❌ Error BD: ' . \\$e->getMessage(); }\" && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"